# Generated by Django 4.1.7 on 2023-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_identity", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("payment_mode", models.CharField(max_length=50)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("Application Web", "Application Web"),
                            ("Blog", "Blog"),
                            ("E-commerce", "E-commerce"),
                            ("Forum", "Forum"),
                            ("One Page", "One Page"),
                            ("Portfolio", "Portfolio"),
                            ("Vitrine", "Vitrine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("site_category", models.CharField(max_length=50)),
                ("site_quantity", models.IntegerField()),
                ("site_cost", models.FloatField()),
                ("db_exist", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "db_category",
                    models.CharField(
                        choices=[("Classique", "Classique"), ("Avancée", "Avancéé")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("db_quantity", models.IntegerField(null=True)),
                ("db_cost", models.FloatField(null=True)),
                ("domain_exist", models.BooleanField(default=False, null=True)),
                (
                    "domain_extension",
                    models.CharField(choices=[], max_length=50, null=True),
                ),
                ("domain_quantity", models.IntegerField(null=True)),
                ("domain_cost", models.FloatField(null=True)),
                ("hosting_exist", models.BooleanField(default=False, null=True)),
                (
                    "hosting_type",
                    models.CharField(
                        choices=[
                            ("Simple", "Simple"),
                            ("Mutualisé", "Mutualisé"),
                            ("WordPress", "WordPress"),
                            ("VPS", "VPS"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("hosting_period", models.IntegerField(null=True)),
                ("hosting_quantity", models.IntegerField(null=True)),
                ("hosting_cost", models.FloatField(null=True)),
                ("maintenance_exist", models.BooleanField(default=False, null=True)),
                (
                    "maintenace_category",
                    models.CharField(
                        choices=[
                            ("Mensuelle", "Mensuelle"),
                            ("Trimestrielle", "Trimestrielle"),
                            ("Semestrielle", "Semestrielle"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("maintenance_quantity", models.IntegerField(null=True)),
                ("maintenance_cost", models.FloatField(null=True)),
            ],
        ),
    ]
