# Generated by Django 4.1.7 on 2023-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_command"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="maintenace_category",
            new_name="maintenance_category",
        ),
        migrations.AlterField(
            model_name="command",
            name="db_quantity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="command",
            name="domain_quantity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="command",
            name="hosting_period",
            field=models.CharField(
                choices=[
                    ("5 ans", "5 ans"),
                    ("2 ans", "2 ans"),
                    ("1 an", "1 an"),
                    ("6 mois", "6 mois"),
                    ("3 mois", "3 mois"),
                    ("1 mois", "1 mois"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="hosting_quantity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="command",
            name="maintenance_quantity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="command",
            name="site_quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
