# Generated by Django 4.1.7 on 2023-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0003_rename_maintenace_category_command_maintenance_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="domain_period",
            field=models.CharField(
                choices=[
                    ("5 ans", "5 ans"),
                    ("4 ans", "4 ans"),
                    ("3 ans", "3 ans"),
                    ("2 ans", "2 ans"),
                    ("1 an", "1 an"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="domain_extension",
            field=models.CharField(
                choices=[(".com", ".com"), (".org", ".org"), (".cd", ".cd")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Virement bancaire", "Virement bancaire"),
                    ("Orange-Money", "Orange-Money"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="site_category",
            field=models.CharField(
                choices=[
                    ("Simple", "Simple"),
                    ("Intermédiaire", "Intermédiaire"),
                    ("Avancé", "Avancé"),
                ],
                max_length=50,
            ),
        ),
    ]
