# Generated by Django 4.1.7 on 2023-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("required_service", models.CharField(max_length=30)),
                ("delivery_delay", models.CharField(max_length=20)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Virement bancaire", "Virement bancaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("budget", models.IntegerField()),
                ("file", models.FileField(upload_to="devis/%Y/%m/%d/")),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("date_posted", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
